### PR TITLE
Multi-language support transformation completed

### PR DESCRIPTION
**Pull request by TheWhiteDog9487**

### CODE REVIEW

**Comment by ThePhaseCat** [comment]
i'll be taking a closer look at this later to make sure everything's good but at a first glance everything seems ok

**Comment by TheWhiteDog9487** [comment]
> had a time to look at it! few things of note...
> 
>     * I'm changing my language and I'm seeing everything change except for the actual input areas? not sure if this is what you intended or if i'm stupid
>       image
> 
>     * noticed you got rid of this and replaced it with %s, which is a nice shortcut! i think it would be useful to add in the top of the advanced mode screen what this %s actually does so users don't get confused at what this replaces depending on where they're typing it! Not sure if you wanted to do it, I can do it if needed, just wanted to bring it to your attention!
>       image
> 
> 
> overall, pretty good! i'll hold off on merging this for a little while in case you want to make any other changes in regards to multi-language support

For the first point, this is the problem I told you in the last PR that I couldn't solve. This is a bug. I tried to reset the content in the input box after changing the language, but nothing happened. I don't know how to fix this problem.
For the second point, I considered that it is indeed necessary to add a description, but I am not a native English speaker (including the current communication with you is using a translator), so I think if you also think this description is necessary, the English text should be written by you, and then I will add the Chinese translation.

**Comment by TheWhiteDog9487** [comment]
In addition, after you switch the language and restart the game, you will see that the Reset button on the right side of the input box can be clicked, and after clicking it, the content of the input box will be changed to the corresponding language.
I know this doesn't look good, and I have also tried to directly replace the text in the text box, but nothing happened. I don't know how to solve it.

**Comment by ThePhaseCat** [comment]
That's ok if the first issue can't be fixed! I'm not sure how to fix it myself, but I don't think it's too much of an issue!

For the second point, I'd be happy to go and do that later today! I'll merge this PR and add the english version into the 1.6 branch and then you can make another PR to add the translation in!

**Review by ThePhaseCat — APPROVED** [review]

**Pull request merged**
