### PR TITLE
Improved multi-language support and translated text, and fixed a lot bugs

### PR DESCRIPTION
**Pull request by TheWhiteDog9487**
I'm very sorry. Last time I was modifying the code and updating a lot of translation keys, I was not clear-headed and caused a lot of bugs. This time I fixed all the ones I saw.

There are three more things to note.
1. I found that using `client.isPaused()` in multiplayer games does not check the client's paused state, so I changed it to `client.currentScreen != null`, which works fine in both multiplayer and single-player games.
2. When testing in a Chinese environment, I found that the content of the translation key `phases-discord-rich-presence.midnightconfig.mainAdvancedModeStateMultiplayerAmount` automatically changed from `"with %d players"` to `"with %s players"`. 
Snipaste_2024-11-09_12-08-54
I checked the code but couldn't find the reason. So I directly changed `%d` to `%s`, and used the order of the two `%s` to control the content replaced. 
3. I found that the number of players displayed in multiplayer games will include myself, which means that if I play in a server with only me, others will see "with 1 players", which is obviously incorrect, so I added -1 after amountOfPlayers

### CODE REVIEW

**Comment by ThePhaseCat** [comment]
no worries! thanks for the fixes/tweaks! I'll be looking at them in the next few days because I'm currently recovering from being sick and I have college work to catch up on (which is more important at the current moment) :(

**Comment by ThePhaseCat** [comment]
i'm still recovering from being sick :(

**Comment by TheWhiteDog9487** [comment]
> i'm still recovering from being sick :(

Don't worry, just review it when you have free time. 
Wish you a speedy recovery from your illness.

**Comment by ThePhaseCat** [comment]
will be able to do this later in the week as this week for college is going to be incredibly busy for me :(

**Review by ThePhaseCat — APPROVED** [review]

**Comment by ThePhaseCat** [comment]
sorry about the delay! thanks for the pr! will be releasing the full 1.6 version hopefully later in the week!

**Pull request merged**
