### PR TITLE
1.21/mod menu fix

### PR DESCRIPTION
**Pull request by Programmer-Timmy**
### Fix Mod Menu Integration

Hi, I noticed that Mod Menu was not working with this mod, so I decided to try and fix it (even though I've never done any Minecraft modding before).

Well, it's fixed now!

I have changed the version to `1.5.1-1.21`. This adds more clarity and makes it easier to update versions `1.20.1` and `1.20.4`, which are among the more commonly used versions. If you don't like it, you can change it!

### CODE REVIEW

**Comment by ThePhaseCat** [comment]
hey!

took a very quick peak at both 1.21 and 1.20.4, and they seem to be working (still need to test the actual rich presence). unfortunately, i have to leave for a pretty long trip (i get back around the 8th next month) and as of right now, i don't have time to fully check everything and merge this pull request, so i'm going to keep this open until i get back. i know this kinda sucks, but i lack the time to properly check over everything and ensure everything is working exactly as expected.

(seriously though thank you for fixing this i've never been able to figure out why it wasn't working but now i see why it wasn't working, tysm!)

**Comment by ThePhaseCat** [comment]
just commenting to say I did not forget about this, will merge this on Saturday alongside adding support for 1.21.1 (while keeping 1.21)

i also did see your issue, will look into that on Saturday as well

**Comment by Programmer-Timmy** [comment]
All good! Thanks for letting me know 😂

**Comment by ThePhaseCat** [comment]
merged the 1.21 version, working on getting a 1.20.4 branch set up, and i'll be bumped back the version to 1.4.1 because this isn't that big of an update on the surface 

tysm again, and sorry again for the super super long wait!

**Comment by Programmer-Timmy** [comment]
Fair 😂. No worries!

**Pull request merged**
